/* Generated by scripts/emit-build-digest.mjs. Do not edit. */

export const ANALYZER_BUILD_DIGEST = "sha256:efcde45907307dea0034e29d7c8bdba5ac51aa8fdb738ac886dd950f999accfc";

export const ADAPTER_REGISTRY_DIGEST = "sha256:ae8da640a4852936e07d554da0d90edec98e26aec00ade144053850c75933143";
