import { readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { ALL_LANGUAGES } from "../../src/core/domain/language.js";
import type { ProjectMap } from "../../src/core/domain/project-map.js";
import type { ResolvedConfig } from "../../src/core/ports/config.port.js";
import { BuildProjectMapUseCase } from "../../src/features/build/build.use-case.js";
import { defaultExtractors } from "../../src/features/build/extractor-set.js";
import { renderMarkdown } from "../../src/features/build/rendering/markdown.js";
import { SystemClock } from "../../src/infrastructure/clock/system.js";
import { CosmiconfigLoader } from "../../src/infrastructure/config/loader.js";
import { GlobbyWalker } from "../../src/infrastructure/filesystem/globby-walker.js";
import { NodeFileReader } from "../../src/infrastructure/filesystem/node-fs.js";
import { ConsoleLogger } from "../../src/infrastructure/logger/console.js";
import { TreeSitterParserRegistry } from "../../src/infrastructure/parser/tree-sitter.js";
import { GitRevisionProvider } from "../../src/infrastructure/revision/git.js";
import { bodyRows, headerRow } from "../support/markdown.js";
import {
	createWorkspace,
	runCli,
	type Workspace,
} from "../support/workspace.js";

const FIXTURE = "python-aiohttp-minimal";
const MD = "PROJECT_MAP.md";
const LEAD = "Generated by project-map. Do not edit by hand.";

async function buildDocument(dir: string): Promise<string> {
	const code = await runCli(dir, ["build"]);
	expect(code).toBe(0);
	return await readFile(path.join(dir, MD), "utf8");
}

async function buildWithFailingEntities(dir: string): Promise<string> {
	const config = await loadFixtureConfig(dir);
	const { map } = await buildWithFailure(dir, config);
	return renderMarkdown(map, config);
}

async function loadFixtureConfig(dir: string): Promise<ResolvedConfig> {
	const config = await new CosmiconfigLoader().load(dir, null);
	if (!config) {
		throw new Error("fixture config missing");
	}
	return config;
}

async function buildWithFailure(
	dir: string,
	config: ResolvedConfig,
): Promise<{ map: ProjectMap }> {
	const logger = new ConsoleLogger(false);
	return await new BuildProjectMapUseCase({
		config,
		walker: new GlobbyWalker(),
		reader: new NodeFileReader(),
		parser: new TreeSitterParserRegistry(ALL_LANGUAGES, logger),
		clock: new SystemClock(),
		logger,
		revision: new GitRevisionProvider(),
		toolVersion: "test",
		extractors: {
			...defaultExtractors(),
			entities: {
				name: "entities",
				extract: () => Promise.reject(new Error("entities blew up")),
			},
		},
	}).execute(dir);
}

describe("map document contract", () => {
	let workspace: Workspace;

	beforeEach(async () => {
		workspace = await createWorkspace(FIXTURE);
	});
	afterEach(async () => {
		await workspace.dispose();
	});

	/* @covers project-map:CTR-003 */
	/* @covers project-map:DLT-020 */
	/* @covers project-map:DLT-025 */
	it("opens with the H1 and the constant lead paragraph", async () => {
		const lines = (await buildDocument(workspace.dir)).split("\n");

		expect(lines[0]).toBe("# Project Map: `aiohttp-minimal`");
		expect(lines[2]).toBe(LEAD);
	});

	/* @covers project-map:DLT-020 */
	it("carries no value that a rebuild alone would change", async () => {
		const markdown = await buildDocument(workspace.dir);

		expect(markdown).not.toContain("## Generation metadata");
		expect(markdown).not.toMatch(/^Coverage: /m);
		expect(markdown).not.toMatch(/\d{4}-\d{2}-\d{2}T\d{2}:\d{2}/);
		expect(markdown).not.toMatch(/Generated by project-map v/);
	});

	/* @covers project-map:CTR-003 */
	it("renders sections in the order the configuration lists them", async () => {
		const markdown = await buildDocument(workspace.dir);
		const headings = [
			"## Bounded contexts",
			"## Domain entities",
			"## Enums",
			"## Storage",
		];

		const positions = headings.map((h) => markdown.indexOf(h));
		expect(positions.every((p) => p > -1)).toBe(true);
		expect(positions).toEqual([...positions].sort((a, b) => a - b));
	});

	/* @covers project-map:DLT-020 */
	it("rejects a configuration naming the removed metadata section", async () => {
		const configPath = path.join(workspace.dir, ".project-map.yaml");
		const config = await readFile(configPath, "utf8");
		await writeFile(
			configPath,
			config.replace("sections:\n", "sections:\n  - metadata\n"),
			"utf8",
		);

		expect(await runCli(workspace.dir, ["build"])).toBe(5);
	});

	/* @covers project-map:DLT-020 */
	it("rejects the removed section named through --only", async () => {
		expect(await runCli(workspace.dir, ["build", "--only", "metadata"])).toBe(
			5,
		);
	});

	/* @covers project-map:INV-002 */
	it("orders collections independently of the absolute path it builds from", async () => {
		const other = await createWorkspace(FIXTURE);
		try {
			const first = await buildDocument(workspace.dir);
			const second = await buildDocument(other.dir);

			expect(second).toBe(first);
		} finally {
			await other.dispose();
		}
	});

	/* @covers project-map:POL-002 */
	it("completes with outbound fetch denied", async () => {
		const realFetch = globalThis.fetch;
		globalThis.fetch = () => {
			throw new Error("network access is forbidden in the build path");
		};
		try {
			const markdown = await buildDocument(workspace.dir);
			expect(markdown).toContain("## Bounded contexts");
		} finally {
			globalThis.fetch = realFetch;
		}
	});
});

describe("map document emission", () => {
	let workspace: Workspace;

	beforeEach(async () => {
		workspace = await createWorkspace(FIXTURE);
	});
	afterEach(async () => {
		await workspace.dispose();
	});

	/* @covers project-map:GA-001 */
	/* @covers project-map:DLT-003 */
	it("regenerates the document whole, keeping nothing from the previous one", async () => {
		const mdPath = path.join(workspace.dir, MD);
		await writeFile(mdPath, "stale marker that must not survive\n", "utf8");

		const regenerated = await buildDocument(workspace.dir);

		expect(regenerated).not.toContain("stale marker");
		expect(regenerated.startsWith("# Project Map: `aiohttp-minimal`")).toBe(
			true,
		);
	});

	/* @covers project-map:GA-001 */
	/* @covers project-map:INV-001 */
	/* @covers project-map:DLT-020 */
	it("emits a byte-identical document on a second build, unnormalized", async () => {
		const first = await buildDocument(workspace.dir);
		const second = await buildDocument(workspace.dir);

		expect(second).toBe(first);
	});
});

describe("rendered anchors", () => {
	let workspace: Workspace;

	beforeEach(async () => {
		workspace = await createWorkspace(FIXTURE);
	});
	afterEach(async () => {
		await workspace.dispose();
	});

	/* @covers project-map:DLT-021 */
	it("names the file that declares a symbol and no line within it", async () => {
		const markdown = await buildDocument(workspace.dir);

		expect(markdown).toContain("Source: `entities/transaction.py`");
		expect(markdown).not.toMatch(/`[^`\n]+\.py:\d+`/);
	});

	/* @covers project-map:DLT-021 */
	it("keeps the line in the JSON companion", async () => {
		await buildDocument(workspace.dir);
		const companion: unknown = JSON.parse(
			await readFile(path.join(workspace.dir, "project-map.json"), "utf8"),
		);

		const lines = entitySourceLines(companion);
		expect(lines.length).toBeGreaterThan(0);
		expect(lines.every((line) => line >= 1)).toBe(true);
	});
});

describe("ranked collections", () => {
	let workspace: Workspace;

	beforeEach(async () => {
		workspace = await createWorkspace(FIXTURE);
	});
	afterEach(async () => {
		await workspace.dispose();
	});

	/* @covers project-map:DLT-022 */
	it("heads the bounded-contexts table with the path and the role alone", async () => {
		const markdown = await buildDocument(workspace.dir);

		const header = headerRow(markdown, "## Bounded contexts");
		expect(header).toEqual(["Path", "Role"]);
	});

	/* @covers project-map:DLT-022 */
	it("carries no reference count on an entity", async () => {
		const markdown = await buildDocument(workspace.dir);

		expect(markdown).not.toMatch(/Referenced from/);
	});

	/* @covers project-map:DLT-022 */
	/* @covers project-map:INV-002 */
	it("keeps the file-count order the dropped column reported", async () => {
		const markdown = await buildDocument(workspace.dir);
		const companion: unknown = JSON.parse(
			await readFile(path.join(workspace.dir, "project-map.json"), "utf8"),
		);

		const ranked = contextsByFileCount(companion);
		expect(ranked.length).toBeGreaterThan(1);
		expect(dataColumn(markdown, "## Bounded contexts")).toEqual(ranked);
	});
});

describe("a value read out of the source", () => {
	let workspace: Workspace;

	beforeEach(async () => {
		workspace = await createWorkspace(FIXTURE);
	});
	afterEach(async () => {
		await workspace.dispose();
	});

	/* @covers project-map:DLT-025 */
	it("survives nowhere as an escaped underscore", async () => {
		const markdown = await buildDocument(workspace.dir);

		expect(markdown).toContain("interactions/pay_transactions");
		expect(markdown).toContain("EVENT_TYPE_TRANSACTION_CREATED");
		expect(markdown).not.toContain("\\_");
	});

	/* @covers project-map:DLT-025 */
	it("renders every cell of the tables it reads as code", async () => {
		const markdown = await buildDocument(workspace.dir);

		const contexts = bodyRows(markdown, "## Bounded contexts");
		expect(contexts.map((row) => row[0])).toContain("`entities`");
		expect(contexts.map((row) => row[1])).toContain("Domain entities");
		expect(bodyRows(markdown, "### Tables")).toContainEqual([
			"`transactions`",
			"`Transaction`",
			"`entities/transaction.py`",
		]);
	});
});

describe("the storage headings", () => {
	let workspace: Workspace;

	beforeEach(async () => {
		workspace = await createWorkspace(FIXTURE);
	});
	afterEach(async () => {
		await workspace.dispose();
	});

	/* @covers project-map:DLT-032 */
	it("head the migration tail without saying how long it is", async () => {
		const markdown = await buildDocument(workspace.dir);

		expect(markdown).toContain("### Tables");
		expect(markdown).toContain("### Recent migrations");
		expect(markdown).not.toMatch(/### Migrations/);
	});
});

describe("a field list", () => {
	let workspace: Workspace;

	beforeEach(async () => {
		workspace = await createWorkspace(FIXTURE);
	});
	afterEach(async () => {
		await workspace.dispose();
	});

	/* @covers project-map:DLT-026 */
	it("is introduced by a label carrying no count", async () => {
		const markdown = await buildDocument(workspace.dir);

		expect(markdown).toContain("Fields:");
		expect(markdown).not.toMatch(/Fields \(\d+\)/);
	});

	/* @covers project-map:DLT-026 */
	it("reports its length by its bullets", async () => {
		const markdown = await buildDocument(workspace.dir);

		expect(fieldBullets(markdown, "### `Transaction`")).toEqual([
			"`transaction_id`",
			"`status`",
			"`amount`",
			"`currency`",
		]);
	});
});

describe("extractor failure isolation", () => {
	let workspace: Workspace;

	beforeEach(async () => {
		workspace = await createWorkspace(FIXTURE);
	});
	afterEach(async () => {
		await workspace.dispose();
	});

	/* @covers project-map:BEH-004 */
	it("records a failing extractor instead of aborting", async () => {
		const config = await loadFixtureConfig(workspace.dir);

		const { map } = await buildWithFailure(workspace.dir, config);

		expect(map.metadata.errors).toEqual([
			{ section: "entities", message: "entities blew up" },
		]);
		expect(map.entities).toEqual([]);
		expect(map.enums.length).toBeGreaterThan(0);
	});

	/* @covers project-map:BEH-004 */
	/* @covers project-map:DLT-020 */
	it("renders the failure under its own heading", async () => {
		const markdown = await buildWithFailingEntities(workspace.dir);

		const errors = markdown.indexOf("## Extraction errors");
		expect(errors).toBeGreaterThan(-1);
		expect(errors).toBeLessThan(markdown.indexOf("## Bounded contexts"));
		expect(markdown).toContain("`entities`: entities blew up");
	});

	/* @covers project-map:BEH-004 */
	it("renders no such heading when every extractor succeeds", async () => {
		const markdown = await buildDocument(workspace.dir);

		expect(markdown).not.toContain("## Extraction errors");
	});
});

function isArray(value: unknown): value is readonly unknown[] {
	return Array.isArray(value);
}

function fieldOf(value: unknown, key: string): unknown {
	return typeof value === "object" && value !== null && key in value
		? Object.getOwnPropertyDescriptor(value, key)?.value
		: undefined;
}

function entitySourceLines(companion: unknown): number[] {
	const entities = fieldOf(companion, "entities");
	if (!isArray(entities)) {
		return [];
	}
	return entities.flatMap((entity) => {
		const line = fieldOf(fieldOf(entity, "source"), "line");
		return typeof line === "number" ? [line] : [];
	});
}

function contextsByFileCount(companion: unknown): string[] {
	const contexts = fieldOf(companion, "contexts");
	if (!isArray(contexts)) {
		return [];
	}
	const rows = contexts.map((context) => ({
		path: String(fieldOf(context, "path")),
		fileCount: Number(fieldOf(context, "fileCount")),
	}));
	rows.sort((a, b) =>
		b.fileCount === a.fileCount
			? a.path.localeCompare(b.path)
			: b.fileCount - a.fileCount,
	);
	return rows.map((row) => row.path);
}

/** The first column, unquoted: the assertion is about order, not rendering. */
function dataColumn(markdown: string, heading: string): string[] {
	return bodyRows(markdown, heading).flatMap((row) =>
		row[0] === undefined ? [] : [row[0].replaceAll("`", "")],
	);
}

function fieldBullets(markdown: string, entityHeading: string): string[] {
	const after = markdown.slice(markdown.indexOf(entityHeading)).split("\n");
	const under = after.slice(after.indexOf("Fields:") + 1);
	const end = under.findIndex((line) => line !== "" && !line.startsWith("- "));
	return under
		.slice(0, end)
		.filter((line) => line.startsWith("- "))
		.map((line) => line.slice(2));
}
