import { readFile, writeFile } from "node:fs/promises";
import * as path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { ALL_LANGUAGES } from "../../src/core/domain/language.js";
import { BuildProjectMapUseCase } from "../../src/features/build/build.use-case.js";
import { defaultExtractors } from "../../src/features/build/extractor-set.js";
import { SystemClock } from "../../src/infrastructure/clock/system.js";
import { CosmiconfigLoader } from "../../src/infrastructure/config/loader.js";
import { GlobbyWalker } from "../../src/infrastructure/filesystem/globby-walker.js";
import { NodeFileReader } from "../../src/infrastructure/filesystem/node-fs.js";
import { ConsoleLogger } from "../../src/infrastructure/logger/console.js";
import { TreeSitterParserRegistry } from "../../src/infrastructure/parser/tree-sitter.js";
import { GitRevisionProvider } from "../../src/infrastructure/revision/git.js";
import {
	createWorkspace,
	runCli,
	type Workspace,
} from "../support/workspace.js";

const FIXTURE = "python-aiohttp-minimal";
const MD = "PROJECT_MAP.md";

const METADATA_ROWS = [
	"Tool version",
	"Config hash",
	"Scanned files",
	"Excluded",
	"Build duration",
	"Language",
	"Frameworks",
	"Errors",
];

function stripNonReproducible(markdown: string): string {
	return markdown
		.replace(/^Generated by project-map v.+$/m, "Generated by project-map")
		.replace(/^\| Build duration\s*\|.*\|$/m, "| Build duration | X |");
}

async function buildDocument(dir: string): Promise<string> {
	const code = await runCli(dir, ["build"]);
	expect(code).toBe(0);
	return await readFile(path.join(dir, MD), "utf8");
}

describe("map document contract", () => {
	let workspace: Workspace;

	beforeEach(async () => {
		workspace = await createWorkspace(FIXTURE);
	});
	afterEach(async () => {
		await workspace.dispose();
	});

	/* @covers project-map:CTR-003 */
	it("opens with the H1 and the two lead paragraphs", async () => {
		const lines = (await buildDocument(workspace.dir)).split("\n");

		expect(lines[0]).toBe("# Project Map: aiohttp-minimal");
		expect(lines.some((l) => /^Generated by project-map v/.test(l))).toBe(true);
		expect(
			lines.some((l) =>
				/^Coverage: \d+ python files? scanned \(\d+ excluded\)\.$/.test(l),
			),
		).toBe(true);
	});

	/* @covers project-map:CTR-003 */
	it("renders generation-metadata rows in the declared order", async () => {
		const markdown = await buildDocument(workspace.dir);
		const start = markdown.indexOf("## Generation metadata");
		expect(start).toBeGreaterThan(-1);

		const rendered = METADATA_ROWS.filter((label) =>
			markdown.includes(`| ${label} `),
		);
		expect(rendered).toEqual(METADATA_ROWS);

		const positions = METADATA_ROWS.map((label) =>
			markdown.indexOf(`| ${label} `, start),
		);
		expect(positions).toEqual([...positions].sort((a, b) => a - b));
	});

	/* @covers project-map:CTR-003 */
	it("renders sections in the order the configuration lists them", async () => {
		const markdown = await buildDocument(workspace.dir);
		const headings = [
			"## Bounded contexts",
			"## Domain entities",
			"## Enums",
			"## Storage",
			"## Generation metadata",
		];

		const positions = headings.map((h) => markdown.indexOf(h));
		expect(positions.every((p) => p > -1)).toBe(true);
		expect(positions).toEqual([...positions].sort((a, b) => a - b));
	});

	/* @covers project-map:INV-002 */
	it("orders collections independently of the absolute path it builds from", async () => {
		const other = await createWorkspace(FIXTURE);
		try {
			const first = await buildDocument(workspace.dir);
			const second = await buildDocument(other.dir);

			expect(stripNonReproducible(second)).toBe(stripNonReproducible(first));
		} finally {
			await other.dispose();
		}
	});

	/* @covers project-map:POL-002 */
	it("completes with outbound fetch denied", async () => {
		const realFetch = globalThis.fetch;
		globalThis.fetch = () => {
			throw new Error("network access is forbidden in the build path");
		};
		try {
			const markdown = await buildDocument(workspace.dir);
			expect(markdown).toContain("## Generation metadata");
		} finally {
			globalThis.fetch = realFetch;
		}
	});
});

describe("map document emission", () => {
	let workspace: Workspace;

	beforeEach(async () => {
		workspace = await createWorkspace(FIXTURE);
	});
	afterEach(async () => {
		await workspace.dispose();
	});

	/* @covers project-map:GA-001 */
	it("regenerates the document whole, keeping nothing from the previous one", async () => {
		const mdPath = path.join(workspace.dir, MD);
		await writeFile(mdPath, "stale marker that must not survive\n", "utf8");

		const regenerated = await buildDocument(workspace.dir);

		expect(regenerated).not.toContain("stale marker");
		expect(regenerated.startsWith("# Project Map: aiohttp-minimal")).toBe(true);
	});

	/* @covers project-map:GA-001 */
	it("emits an identical document on a second build over an unchanged tree", async () => {
		const first = await buildDocument(workspace.dir);
		const second = await buildDocument(workspace.dir);

		expect(stripNonReproducible(second)).toBe(stripNonReproducible(first));
	});
});

describe("extractor failure isolation", () => {
	let workspace: Workspace;

	beforeEach(async () => {
		workspace = await createWorkspace(FIXTURE);
	});
	afterEach(async () => {
		await workspace.dispose();
	});

	/* @covers project-map:BEH-004 */
	it("records a failing extractor in metadata instead of aborting", async () => {
		const logger = new ConsoleLogger(false);
		const config = await new CosmiconfigLoader().load(workspace.dir, null);
		if (!config) {
			throw new Error("fixture config missing");
		}
		const extractors = defaultExtractors();

		const { map } = await new BuildProjectMapUseCase({
			config,
			walker: new GlobbyWalker(),
			reader: new NodeFileReader(),
			parser: new TreeSitterParserRegistry(ALL_LANGUAGES, logger),
			clock: new SystemClock(),
			logger,
			revision: new GitRevisionProvider(),
			toolVersion: "test",
			extractors: {
				...extractors,
				entities: {
					name: "entities",
					extract: () => Promise.reject(new Error("entities blew up")),
				},
			},
		}).execute(workspace.dir);

		expect(map.metadata.errors).toEqual([
			{ section: "entities", message: "entities blew up" },
		]);
		expect(map.entities).toEqual([]);
		expect(map.enums.length).toBeGreaterThan(0);
	});
});
